### ISSUE TITLE
Unable to use theme

### ISSUE THREAD

**Issue by svipas** [anaganisk/vscode-onedark-plus#1]
`Problem setting theme: Unable to load /home/svipben/.vscode/extensions/anaganisk.theme-onedark-plus-1.0.3/themes/OneDarkPlus.tmTheme: Problems parsing theme file: Near offset 30894: unexpected closed tag ~~~string>
`

**Comment by anaganisk** [comment]
@svipben Could you please let me know if you are getting this error after an update or is it a fresh installation?

**Comment by svipas** [comment]
@anaganisk It's first time I downloaded this theme, I'm using VS Code: 1.11, my OS is Linux Ubuntu 16.04. Yeah it's fresh installation.

**Comment by anaganisk** [comment]
@svipben It was a small issue which I overlooked, sorry for the inconvenience caused, I fixed and pushed an update, you must no more see that error, please uninstall the theme and re-install it it you must be able to use the new  v1.0.4 update. Thanks for reporting.

**Comment by svipas** [comment]
@anaganisk No problem :+1: Yeah, right now working!

**Comment by anaganisk** [comment]
@svipben Please let me know after re-installing it, and if the error doesn't persist on your side I will close this issue, thanks.

**Comment by svipas** [comment]
@anaganisk You can close the issue, it's working right now.

**Comment by anaganisk** [comment]
Commit b2f7cd2118a2739a18b9218385343e2067c091a7 closes #1
